export interface DealerContact {
  dealerId: number;
  name: string;
  email: string;
  itemType: "FRAME" | "LENS" | "BOTH";
  status: "ACTIVE" | "INACTIVE";
}

export interface DealerFormValues {
  name: string;
  email: string;
  itemType: "FRAME" | "LENS" | "BOTH";
}

export interface LowStockItem {
  dealerId: number;
  dealerName: string;
  itemType: "FRAME" | "LENS" | "BOTH";
  itemName: string;
  currentStock: number;
  neededStock: number;
  threshold: number;
}

export interface LowInventoryData {
  lowStockItems: LowStockItem[];
  totalItems: number;
  generatedEmail: {
    subject: string;
    body: string;
    status: "DRAFT" | "SENT" | "REPLIED" | "FULFILLED";
    autoGenerated: boolean;
  };
}

export interface DealerEmailStatus {
  emailId: number;
  dealerId: number;
  dealerName: string;
  subject: string;
  status: "DRAFT" | "SENT" | "REPLIED" | "FULFILLED";
  createdAt: string;
  sentAt: string | null;
}

export interface SentEmailsDashboard {
  emails: DealerEmailStatus[];
  totalEmails: number;
  statusCounts: {
    DRAFT: number;
    SENT: number;
    REPLIED: number;
    FULFILLED: number;
  };
}