package com.myopty.workflow.service;

import com.myopty.workflow.model.Dealer;
import com.myopty.workflow.repository.DealerRepository;
import org.springframework.stereotype.Service;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Service
public class DealerService {

    private final DealerRepository dealerRepository;

    public DealerService(DealerRepository dealerRepository) {
        this.dealerRepository = dealerRepository;
    }

    public Dealer createDealer(String name, String email, String itemType) {
        Dealer dealer = new Dealer();
        dealer.setName(name);
        dealer.setEmail(email);
        dealer.setType(itemType);
        dealer.setActive(true);
        return dealerRepository.save(dealer);
    }

    public Dealer updateDealer(Integer dealerId, String name, String email, String itemType, boolean active) {
        Dealer dealer = dealerRepository.findById(dealerId)
                .orElseThrow(() -> new RuntimeException("Dealer not found with id: " + dealerId));
        dealer.setName(name);
        dealer.setEmail(email);
        dealer.setType(itemType);
        dealer.setActive(active);
        return dealerRepository.save(dealer);
    }

    public List<Dealer> getAllDealers() {
        return dealerRepository.findAll();
    }

    public List<Dealer> getActiveDealers() {
        return dealerRepository.findAllActive();
    }

    public Optional<Dealer> getDealerByEmail(String email) {
        return dealerRepository.findByEmail(email);
    }

    public void deleteDealer(Integer dealerId) {
        dealerRepository.deleteById(dealerId);
    }

    /**
     * Calculate needed stock based on low inventory thresholds.
     * This is a placeholder calculation.
     */
    public List<Map<String, Object>> calculateLowStock() {
        List<Map<String, Object>> result = new java.util.ArrayList<>();
        return result;
    }

    /**
     * Generate a stock-request email draft based on calculated needs.
     */
    public Map<String, Object> generateStockRequestEmail(Integer dealerId) {
        Map<String, Object> emailData = new HashMap<>();
        Dealer dealer = dealerRepository.findById(dealerId)
                .orElseThrow(() -> new RuntimeException("Dealer not found with id: " + dealerId));
        emailData.put("dealer", dealer);
        emailData.put("subject", "Stock Request - " + dealer.getName());
        emailData.put("body", "Dear " + dealer.getName() + ",\n\nPlease supply the following items:\n\n---\n\nBest regards,\nMyOpty Team");
        emailData.put("status", "DRAFT");
        emailData.put("autoGenerated", true);
        return emailData;
    }
}