"use client";

import { useState, useEffect } from "react";
import { dealerApi } from "@/features/workflow/api";

interface LowStockItem {
  dealerId: number;
  dealerName: string;
  itemType: "FRAME" | "LENS" | "BOTH";
  itemName: string;
  currentStock: number;
  neededStock: number;
  threshold: number;
}

interface LowInventoryData {
  lowStockItems: LowStockItem[];
  totalItems: number;
  generatedEmail: {
    subject: string;
    body: string;
    status: "DRAFT" | "SENT" | "REPLIED" | "FULFILLED";
    autoGenerated: boolean;
  };
}

export default function LowInventoryPage() {
  const [data, setData] = useState<LowInventoryData>({
    lowStockItems: [],
    totalItems: 0,
    generatedEmail: {
      subject: "",
      body: "",
      status: "DRAFT",
      autoGenerated: false,
    },
  });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      try {
        // Fetch low stock calculation
        const calcResult = await dealerApi.calculateLowStock();
        // Fetch generated email
        const emailResult = await dealerApi.generateStockRequestEmail(1); // Using default dealer ID 1
        
        setData({
          lowStockItems: calcResult.data || [],
          totalItems: calcResult.data?.length || 0,
          generatedEmail: emailResult.data || {
            subject: "",
            body: "",
            status: "DRAFT",
            autoGenerated: false,
          },
        });
      } catch (err: any) {
        setError(err.message || "Failed to load low inventory data");
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  if (loading) {
    return <div className="min-h-80 flex items-center justify-center">Loading...</div>;
  }

  if (error) {
    return <div className="p-4 text-red-600">Error: {error}</div>;
  }

  return (
    <div className="p-6">
      <h2 className="text-2xl font-bold mb-4">Low Inventory</h2>
      
      <div className="bg-white rounded p-4 shadow-sm mb-6">
        <h3 className="text-lg font-medium mb-3">Auto-Calculated Stock Needs</h3>
        {data.lowStockItems.length === 0 && (
          <p className="text-sm text-gray-500">No low stock items</p>
        )}
        <div className="overflow-x-auto">
          <table className="min-w-full rounded border">
            <thead>
              <tr className="bg-gray-50">
                <th className="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Dealer</th>
                <th className="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item Type</th>
                <th className="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item</th>
                <th className="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Current Stock</th>
                <th className="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Needed</th>
                <th className="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Threshold</th>
              </thead>
              <tbody>
                {data.lowStockItems.map((item) => (
                  <tr key={item.dealerId} className="border-b">
                    <td className="p-3">{item.dealerName}</td>
                    <td className="p-3">
                      <span className="text-xs capitalize font-semibold px-2 py-1 rounded bg-blue-100 text-blue-800">
                        {item.itemType}
                      </span>
                    </td>
                    <td className="p-3">{item.itemName}</td>
                    <td className="p-3">{item.currentStock}</td>
                    <td className="p-3">{item.neededStock}</td>
                    <td className="p-3">{item.threshold}</td>
                  </tr>
                ))}
                {data.lowStockItems.length === 0 && (
                  <tr>
                    <td colSpan="6" className="p-4 text-center text-gray-500">
                      No low stock items
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </table>
        </div>
      </div>
      
      {/* Auto-Generated Email */}
      <div className="bg-white rounded p-4 shadow-sm mb-6">
        <h3 className="text-lg font-medium mb-3">Auto-Generated Stock Request Email</h3>
        <p className="text-sm text-gray-500 mb-2">
          {data.generatedEmail.autoGenerated ? "Auto-generated" : "Manual"}
        </p>
        <p className="text-sm text-gray-500">Status: {data.generatedEmail.status}</p>
        <textarea
          rows={5}
          readOnly
          className="w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-primary-500 mt-2"
          style={{ height: '200px' }}
        >
          {data.generatedEmail.body}
        </textarea>
        
        <div className="mt-4">
          <button
            onClick={() => navigator.clipboard.writeText(data.generatedEmail.body)}
            className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition-colors"
            title="Copy email body to clipboard"
          >
            Copy Email Body
          </button>
          <button
            onClick={() => alert("Email draft ready for review and sending")}
            className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors ms-2"
          >
            Review & Send
          </button>
        </div>
      </div>
    </div>
  );
}